version: '3.2'
services:
  jolitickets_db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB:
        ticketis_dev
        
